---
- name: include_tasks installs/install_on_redhat.yml
  include_tasks: installs/install_on_redhat.yml
  when: ansible_os_family == 'RedHat'
  tags: package-install

- name: include_tasks installs/install_on_suse.yml
  include_tasks: installs/install_on_suse.yml
  when: ansible_os_family == 'Suse'
  tags: package-install

- name: include installs/install_on_debian.yml
  include_tasks: installs/install_on_debian.yml
  tags: package-install
  when: ansible_os_family == 'Debian'

- name: include_tasks installs/install_on_clear.yml
  include_tasks: installs/install_on_clear.yml
  when: ansible_os_family == 'ClearLinux'
  tags: package-install

- name: get ceph version
  command: ceph --version
  changed_when: false
  check_mode: no
  register: ceph_version

- name: set_fact ceph_version
  set_fact:
    ceph_version: "{{ ceph_version.stdout.split(' ')[2] }}"

- name: set_fact ceph_release - override ceph_release with ceph_stable_release
  set_fact:
    ceph_release: "{{ ceph_stable_release }}"
  when:
    - ceph_origin == 'repository'
    - ceph_repository not in ['dev', 'rhcs', 'custom']
  tags: always

- name: include create_rbd_client_dir.yml
  include_tasks: create_rbd_client_dir.yml

- name: include configure_cluster_name.yml
  include_tasks: configure_cluster_name.yml

- name: include configure_memory_allocator.yml
  include_tasks: configure_memory_allocator.yml
  when:
    - (ceph_tcmalloc_max_total_thread_cache | int) > 0
    - osd_objectstore == 'filestore'
    - (ceph_origin == 'repository' or ceph_origin == 'distro')
