---
- name: check for a ceph mon socket
  shell: stat --printf=%n {{ rbd_client_admin_socket_path }}/{{ cluster }}-mon*.asok
  changed_when: false
  failed_when: false
  check_mode: no
  register: mon_socket_stat
  when: inventory_hostname in groups.get(mon_group_name, [])

- name: check if the ceph mon socket is in-use
  command: grep -q {{ mon_socket_stat.stdout }} /proc/net/unix
  changed_when: false
  failed_when: false
  check_mode: no
  register: mon_socket
  when:
    - inventory_hostname in groups.get(mon_group_name, [])
    - mon_socket_stat.rc == 0

- name: remove ceph mon socket if exists and not used by a process
  file:
    name: "{{ mon_socket_stat.stdout }}"
    state: absent
  when:
    - inventory_hostname in groups.get(mon_group_name, [])
    - mon_socket_stat.rc == 0
    - mon_socket.rc == 1

- name: check for a ceph osd socket
  shell: |
    stat --printf=%n {{ rbd_client_admin_socket_path }}/{{ cluster }}-osd*.asok
  changed_when: false
  failed_when: false
  check_mode: no
  register: osd_socket_stat
  when: inventory_hostname in groups.get(osd_group_name, [])

- name: check if the ceph osd socket is in-use
  command: grep -q {{ osd_socket_stat.stdout }} /proc/net/unix
  changed_when: false
  failed_when: false
  check_mode: no
  register: osd_socket
  when:
    - inventory_hostname in groups.get(osd_group_name, [])
    - osd_socket_stat.rc == 0

- name: remove ceph osd socket if exists and not used by a process
  file:
    name: "{{ osd_socket_stat.stdout }}"
    state: absent
  when:
    - inventory_hostname in groups.get(osd_group_name, [])
    - osd_socket_stat.rc == 0
    - osd_socket.rc == 1

- name: check for a ceph mds socket
  shell: |
    stat --printf=%n {{ rbd_client_admin_socket_path }}/{{ cluster }}-mds*.asok
  changed_when: false
  failed_when: false
  check_mode: no
  register: mds_socket_stat
  when: inventory_hostname in groups.get(mds_group_name, [])

- name: check if the ceph mds socket is in-use
  command: grep -q {{ mds_socket_stat.stdout }} /proc/net/unix
  changed_when: false
  failed_when: false
  check_mode: no
  register: mds_socket
  when:
    - inventory_hostname in groups.get(mds_group_name, [])
    - mds_socket_stat.rc == 0

- name: remove ceph mds socket if exists and not used by a process
  file:
    name: "{{ mds_socket_stat.stdout }}"
    state: absent
  when:
    - inventory_hostname in groups.get(mds_group_name, [])
    - mds_socket_stat.rc == 0
    - mds_socket.rc == 1

- name: check for a ceph mgr socket
  shell: |
    stat --printf=%n {{ rbd_client_admin_socket_path }}/{{ cluster }}-mgr*.asok
  changed_when: false
  failed_when: false
  check_mode: no
  register: mgr_socket_stat
  when: inventory_hostname in groups.get(mgr_group_name, [])

- name: check if the ceph mgr socket is in-use
  command: grep -q {{ mgr_socket_stat.stdout }} /proc/net/unix
  changed_when: false
  failed_when: false
  check_mode: no
  register: mgr_socket
  when:
    - inventory_hostname in groups.get(mgr_group_name, [])
    - mgr_socket_stat.rc == 0

- name: remove ceph mgr socket if exists and not used by a process
  file:
    name: "{{ mgr_socket_stat.stdout }}"
    state: absent
  when:
    - inventory_hostname in groups.get(mgr_group_name, [])
    - mgr_socket_stat.rc == 0
    - mgr_socket.rc == 1
