---
# Liet ke danh sach tat ca cac pool can thay set flag
- name: collect all the pools
  command: >
    {{ container_exec_cmd }} rados --cluster {{ cluster }} lspools
  changed_when: false
  register: ceph_pools
  check_mode: no

# Dam bao cac pool không bi xoa hay thay doi
- name: secure the cluster
  command: >
    {{ container_exec_cmd }} ceph --cluster {{ cluster }} osd pool set {{ item[0] }} {{ item[1] }} true
  changed_when: false
  with_nested:
    - "{{ ceph_pools.stdout_lines|default([]) }}"
    - "{{ secure_cluster_flags }}"
