---
- hosts: ceph02
  vars:
    cluster: ceph
    osd_objectstore: filestore
    _devices: /dev/vde
    journal_size: 5120
    block_db_size: 5G
    osd_crush_location:
    crush_rule_config: false
    crush_rule_hdd:
      name: HDD
      root: default
      type: host
      class: hdd
      default: false
    crush_rule_ssd:
      name: SSD
      root: default
      type: host
      class: ssd
      default: false
    crush_rules:
      - "{{ crush_rule_hdd }}"
      - "{{ crush_rule_ssd }}"  
    mon_group_name: mons
  tasks: 
    - name: Create crush
      command: "{{ hostvars[groups[mon_group_name][0]]['container_exec_cmd'] | default('') }} ceph --cluster {{ cluster }} osd crush rule {{ 'create-replicated' if item.class is defined else 'create-simple' }} {{ item.name }} {{ item.root }} {{ item.type }} {{ item.class | default('') }}"
      changed_when: false
      with_items: "{{ hostvars[groups[mon_group_name][0]]['crush_rules'] | default(crush_rules) | unique }}"
      delegate_to: '{{ groups[mon_group_name][0] }}'
      run_once: true
