---
- hosts: ceph02
  vars:
    cluster: ceph
    osd_objectstore: filestore
    _devices: /dev/vde
    journal_size: 5120
    block_db_size: 5G
  tasks: 
    - name: look up for ceph-volume rejected devices
      ceph_volume:
        cluster: "{{ cluster }}"
        action: "inventory"
      register: rejected_devices
    - debug: 
        var: rejected_devices.stdout
