- hosts: ceph01
  vars:
    mon_group_name: mons
    rbd_client_admin_socket_path: /var/run/ceph
    cluster: ceph
  tasks:
    - name: check for a ceph mon socket
      shell: stat --printf=%n {{ rbd_client_admin_socket_path }}/{{ cluster }}-mon*.asok
      changed_when: false
      failed_when: false
      check_mode: no
      register: mon_socket_stat
      run_once: true
      delegate_to: "{{ item }}"
      with_items: "{{ groups.get(mon_group_name, []) }}"
    - debug: var=mon_socket_stat.results
#    - debug: 
#        msg: "{{ mon_socket_stat.stdout }}"
#      with_items: "{{ mon_socket_stat.results }}"
#    - debug: msg="{{ mon_socket_stat }}"
    - name: check if the ceph mon socket is in-use
      command: grep -q {{ item.stdout }} /proc/net/unix
#      command: grep -q /var/run/ceph/ceph-mon.ceph01.asok /proc/net/unix
      changed_when: false
      failed_when: false
      check_mode: no
      register: mon_socket
      run_once: true
      with_items: "{{ mon_socket_stat.results }}"
      when:
        - item.rc == 0
    - debug: var=mon_socket.results

    - name: set_fact running_mon - non_container
      set_fact:
        running_mon: "{{ hostvars[item.item.item]['inventory_hostname'] }}"
      with_items: "{{ mon_socket.results }}"
      run_once: true
      when:
        - item.rc is defined
#        - item.rc == 0
    - debug: var=running_mon
