---
- name: Zabbix-server
  yum:
    name:
      - zabbix-server-mysql
      - zabbix-agent
      - zabbix-web-mysql  
    state: installed

- name: Ensure MariaDB is running.
  service: name=zabbix-server state=started enabled=yes

#- name: Import database
#  shell: zcat /usr/share/doc/zabbix-server-mysql*/create.sql.gz | mysql -uzabbix -pzabbix zabbix

- name: Import file.sql similar to mysql -u <username> -p <password> < hostname.sql
  mysql_db:
    state: import
    login_user: zabbix
    login_password: zabbix
    login_host: localhost
    name: zabbix
    target: /usr/share/doc/zabbix-server-mysql-4.4.9/create.sql.gz

