- name: Add zabbix repository
  yum_repository:
    name: zabbix
    baseurl: https://repo.zabbix.com/zabbix/3.0/rhel/7/$basearch/
    gpgkey: https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX
    enabled: 1
    gpgcheck: 1
    file: zabbix
    description: Zabbix Official Repository - $basearch

- name: Add zabbix-non-supported repository
  yum_repository:
    name: zabbix-non-supported
    baseurl: https://repo.zabbix.com/non-supported/rhel/7/$basearch/
    gpgkey: https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX
    enabled: 1
    gpgcheck: 1
    file: zabbix
    description: Zabbix Official Repository non-supported - $basearch
