---
- name: Check /etc/zabbix/zabbix_agentd.conf.orig existed
  stat:
    path: /etc/zabbix/zabbix_agentd.conf.orig
  register: zabbix_agentd_conf_orig
#- debug: var=zabbix_agentd.conf.orig.stdout_lines

- name: Backup file config zabbix_agentd.conf
  copy:
    src: /etc/zabbix/zabbix_agentd.conf
    dest: /etc/zabbix/zabbix_agentd.conf.orig
  when:
    - not zabbix_agentd_conf_orig.stat.exists

- name: Config file /etc/zabbix/zabbix_agentd.conf
  template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
